=begin

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end

def sum_even_fibs(limit)
  total = 2
  last_fib = 3
  new_fib = 5
  until new_fib > limit
    total += new_fib if new_fib.even?
    temp = new_fib
    new_fib += last_fib
    last_fib = temp
  end
  total
end

# Driver test
p sum_even_fibs(4_000_000) == 4613732
